# Generated by Django 3.0.8 on 2020-09-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
