# Generated by Django 3.0.8 on 2020-09-17 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('rating', models.CharField(choices=[('1', 'Not so good...'), ('2', 'Could be better'), ('3', 'It was alright'), ('4', 'Pretty good...'), ('5', 'AMAZING!')], default='3', max_length=1)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Record')),
            ],
        ),
    ]
